### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by wasteduk** [MarvAmBass/docker-firetv-server#2]
Is it possible to reduce the frequency of the polling? I am getting error 500 when making requests of the server.
`InvalidCommandError: ('Unknown command: 70736944', 1886611780, (544825708, 1702326096)),
172.18.0.1 - - [08/Sep/2018 14:00:34] "GET /devices/state/default HTTP/1.1" 500 -,
[2018-09-08 14:00:45,176] ERROR in app: Exception on /devices/state/default [GET],
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app,
    response = self.full_dispatch_request(),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request,
    rv = self.handle_user_exception(e),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception,
    reraise(exc_type, exc_value, tb),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 120, in device_state,
    return jsonify(state=devices[device_id].state),
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 89, in state,
    if not self._screen_on:,
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 230, in _screen_on,
    return self._dump_has('power', 'Display Power', 'state=ON'),
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 288, in _dump_has,
    return self._dump(service, grep=grep).strip().find(search) > -1,
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 277, in _dump,
    return self._adb.Shell('dumpsys {0} | grep "{1}"'.format(service, grep)),
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 366, in Shell,
    timeout_ms=timeout_ms),
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 406, in Command,
    return ''.join(cls.StreamingCommand(usb, service, command, timeout_ms)),
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 433, in StreamingCommand,
    timeout_ms=timeout_ms),
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 369, in Open,
    timeout_ms=timeout_ms),
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 247, in Read,
    'Unknown command: %x' % cmd, cmd, (arg0, arg1)),
InvalidCommandError: ('Unknown command: 5e59414b', 1582907723, (16777217, 0)),
172.18.0.1 - - [08/Sep/2018 14:00:45] "GET /devices/state/default HTTP/1.1" 500 -,`

**Steps to reproduce**

1. Server running, Homeassistant running.
2. Start an activity, e.g. start plex and skip though some photos
3. at random the server will report Error 500 and will not recover.

Can force the error.
1. Server running, Homeassistant running.
2. open URL http://<serverip>:5556/devices/list
3. hit refresh on the devices list till error 500.

**Workaround**
Restart the server

**Comment by wasteduk** [comment]
This is a better example of the start of an error 500.

`INFO:werkzeug:172.18.0.1 - - [08/Sep/2018 16:03:08] "GET /devices/state/default HTTP/1.1" 200 -,
172.18.0.3 - - [08/Sep/2018 16:03:13] "GET /devices/action/default/turn_on HTTP/1.1" 200 -,
INFO:werkzeug:172.18.0.3 - - [08/Sep/2018 16:03:13] "GET /devices/action/default/turn_on HTTP/1.1" 200 -,
INFO:werkzeug:172.18.0.1 - - [08/Sep/2018 16:03:17] "GET /devices/default/apps/com.plexapp.android/start HTTP/1.1" 200 -,
WARNING:root:Couldn't get current app, reply was   mCurrentFocus=null,
ERROR:flask.app:Exception on /devices/state/default [GET],
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app,
    response = self.full_dispatch_request(),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request,
    rv = self.handle_user_exception(e),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception,
    reraise(exc_type, exc_value, tb),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 120, in device_state,
    return jsonify(state=devices[device_id].state),
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 95, in state,
    if self._launcher:,
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 245, in _launcher,
    return self.current_app["package"] == PACKAGE_LAUNCHER,
TypeError: 'NoneType' object has no attribute '__getitem__',
172.18.0.1 - - [08/Sep/2018 16:03:18] "GET /devices/state/default HTTP/1.1" 500 -,
INFO:werkzeug:172.18.0.1 - - [08/Sep/2018 16:03:18] "GET /devices/state/default HTTP/1.1" 500 -`

Hope this helps.

**Comment by MarvAmBass** [comment]
Hi @wasteduk 
It seems to be a problem with plex right? Or is it the server which throws the error - maybe you should check if a local install of this server solves the problem. If not then you should ask the guys who wrote the server. This is just a docker container repo which creates a container for the script some other guy/team wrote.
